package com.ThaumiumAE2.ThaumiumAE2.Mixins;

import appeng.api.storage.StorageChannel;
import appeng.api.storage.data.IAEStack;
import com.ThaumiumAE2.ThaumiumAE2.Interfaces.ITAE2EssentiaStack;
import org.spongepowered.asm.mixin.Final;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Mutable;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.gen.Invoker;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

 @Mixin(StorageChannel.class)
 public class StorageChannelMixin {

     @Shadow(remap = false) // remap=false assumes you are not mapping the private field
     @Final
     @Mutable
     private static StorageChannel[] $VALUES;

     @Invoker("<init>")
     private static StorageChannel invokeStorageChannelConstructor(String enumName, int ordinal, Class<? extends IAEStack> type) {
         // Implementation is generated by Mixin
         throw new UnsupportedOperationException();
     }

     @Inject(method = "<clinit>", at = @At(value = "FIELD", target = "Lappeng/api/storage/StorageChannel;$VALUES:[Lappeng/api/storage/StorageChannel;", shift = At.Shift.AFTER), remap = false)
     private static void tae2$injectEssentiaChannel(CallbackInfo ci) {

         int nextOrdinal = $VALUES.length;

         StorageChannel essentiaChannel = invokeStorageChannelConstructor("ESSENTIA", nextOrdinal, ITAE2EssentiaStack.class);

        StorageChannel[] newValues = new StorageChannel[nextOrdinal + 1];
        System.arraycopy($VALUES, 0, newValues, 0, nextOrdinal);
        newValues[nextOrdinal] = essentiaChannel;
        $VALUES = newValues;

     }
 }
